FROM golang:alpine3.19 AS builder

RUN apk update && apk add --no-cache git
RUN apk add --no-cache make
#FROM golang:1.23 AS build
WORKDIR /go/src
 
COPY *.mod *.sum ./
RUN go mod download
COPY . .

EXPOSE ${API_PORT}
ENTRYPOINT [ "/go/src/bin/api" ]