// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * user_authorization service - OpenAPI 3.0
 *
 * Сервис авторизации пользователей
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// PersonsAPIService is a service that implements the logic for the PersonsAPIServicer
// This service should implement the business logic for every endpoint for the PersonsAPI API.
// Include any external packages or services that will be required by this service.
type PersonsAPIService struct {
}

// NewPersonsAPIService creates a default api service
func NewPersonsAPIService() *PersonsAPIService {
	return &PersonsAPIService{}
}

// PersonsList - Persons list
func (s *PersonsAPIService) PersonsList(ctx context.Context) (ImplResponse, error) {
	// TODO - update PersonsList with the required logic for this service method.
	// Add api_persons_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Person{}) or use other options such as http.Ok ...
	// return Response(200, []Person{}), nil

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PersonsList method not implemented")
}

// GetPersonByUUID - Find person by uuid
func (s *PersonsAPIService) GetPersonByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update GetPersonByUUID with the required logic for this service method.
	// Add api_persons_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Person{}) or use other options such as http.Ok ...
	// return Response(200, Person{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetPersonByUUID method not implemented")
}

// ChangePersonByUUUID - change person by uuid
func (s *PersonsAPIService) ChangePersonByUUUID(ctx context.Context, uuid string, person Person) (ImplResponse, error) {
	// TODO - update ChangePersonByUUUID with the required logic for this service method.
	// Add api_persons_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Person{}) or use other options such as http.Ok ...
	// return Response(200, Person{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ChangePersonByUUUID method not implemented")
}

// DeletePersonByUUUID - delete person by uuid
func (s *PersonsAPIService) DeletePersonByUUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update DeletePersonByUUUID with the required logic for this service method.
	// Add api_persons_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeletePersonByUUUID method not implemented")
}
