// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * user_authorization service - OpenAPI 3.0
 *
 * Сервис авторизации пользователей
 *
 * API version: 1.0.0
 */

package main

import (
	openapi2 "github.com/donskova1ex/user_authorization/openapi"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	PermissionsAPIService := openapi2.NewPermissionsAPIService()
	PermissionsAPIController := openapi2.NewPermissionsAPIController(PermissionsAPIService)

	PersonsAPIService := openapi2.NewPersonsAPIService()
	PersonsAPIController := openapi2.NewPersonsAPIController(PersonsAPIService)

	RolesAPIService := openapi2.NewRolesAPIService()
	RolesAPIController := openapi2.NewRolesAPIController(RolesAPIService)

	UsersAPIService := openapi2.NewUsersAPIService()
	UsersAPIController := openapi2.NewUsersAPIController(UsersAPIService)

	router := openapi2.NewRouter(PermissionsAPIController, PersonsAPIController, RolesAPIController, UsersAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
