openapi: 3.0.0
info:
  title: user_authorization service - OpenAPI 3.0
  description: |-
    Сервис авторизации пользователей
  version: 1.0.0
servers:
  - url: https://user-authorization.swagger.io/api/v1
tags:
  - name: users
    description: Everything about users
  - name: persons
    description: Everything about user person
  - name: roles
    description: Everything about roles
  - name: permission
    description: Everything about permissions
paths:
  /users:
    get:
      tags:
        - users
      summary: Users list
      description: users list
      operationId: usersList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
        '204':
          description: empty list
  /users/{uuid}:
    get:
      tags:
        - users
      summary: Find user by uuid
      description: returns a single user
      operationId: getUserByUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of user to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        '400':
          description: user not changed
        '404':
          description: user not found
    put:
      tags:
        - users
      summary: change user by uuid
      description: change a single user
      operationId: changeUserByUUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of changing user
          required: true
          schema:
            type: string
      requestBody:
        description: update user
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        '400':
          description: invalid uuid supplied
        '404':
          description: user not found
    delete:
      tags:
        - users
      summary: delete user by uuid
      description: delete a single user
      operationId: deleteUserByUUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of delete user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid uuid supplied
        '404':
          description: user not found
  /persons:
    get:
      tags:
        - persons
      summary: Persons list
      description: persons list
      operationId: personsList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/person"
        '204':
          description: empty list
  /persons/{uuid}:
    get:
      tags:
        - persons
      summary: Find person by uuid
      description: returns a single person
      operationId: getPersonByUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of person to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/person"
        '400':
          description: invalid uuid supplied
        '404':
          description: person not found
    put:
      tags:
        - persons
      summary: change person by uuid
      description: change a single person
      operationId: changePersonByUUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of changing person
          required: true
          schema:
            type: string
      requestBody:
        description: update person
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/person"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/person"
        '400':
          description: invalid uuid supplied
        '404':
          description: person not found
    delete:
      tags:
        - persons
      summary: delete person by uuid
      description: delete a single person
      operationId: deletePersonByUUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of delete person
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid uuid supplied
        '404':
          description: person not found
  /roles:
    get:
      tags:
        - roles
      summary: Roles list
      description: roles list
      operationId: rolesList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/role"
        '204':
          description: empty list
  /roles/{uuid}:
    get:
      tags:
        - roles
      summary: Find role by uuid
      description: returns a single role
      operationId: getRoleByUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of role to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/role"
        '400':
          description: invalid uuid supplied
        '404':
          description: role not found
    put:
      tags:
        - roles
      summary: change role by uuid
      description: change a single role
      operationId: changeRoleByUUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of changing role
          required: true
          schema:
            type: string
      requestBody:
        description: update role
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/role"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/role"
        '400':
          description: invalid uuid supplied
        '404':
          description: role not found
    delete:
      tags:
        - roles
      summary: delete role by uuid
      description: delete a single role
      operationId: deleteRoleByUUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of delete role
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid uuid supplied
        '404':
          description: role not found
  /permissions:
    get:
      tags:
        - permissions
      summary: Permissions list
      description: permissions list
      operationId: permissionsList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/permission"
        '204':
          description: empty list
  /permissions/{uuid}:
    get:
      tags:
        - permissions
      summary: Find permission by uuid
      description: returns a single permission
      operationId: getPermissionByUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of permission to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permission"
        '400':
          description: invalid uuid supplied
        '404':
          description: permission not found
    put:
      tags:
        - permissions
      summary: change permission by uuid
      description: change a single permission
      operationId: changePermissionByUUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of changing permission
          required: true
          schema:
            type: string
      requestBody:
        description: update permission
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/permission"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/permission"
        '400':
          description: invalid uuid supplied
        '404':
          description: permission not found
    delete:
      tags:
        - permissions
      summary: delete permission by uuid
      description: delete a single permission
      operationId: deletePermissionByUUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of delete permission
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid uuid supplied
        '404':
          description: permission not found
components:
  schemas:
    user:
      required:
        - user_name
      type: object
      properties:
        uuid:
          type: string
          example: 123123
        user_name:
          type: string
          example: ivanov.i
    role:
      required:
        - role_name
      type: object
      properties:
        uuid:
          type: string
          example: 123123
        user_name:
          type: string
          example: loan manager
    permission:
      required:
        - permissions_name
      properties:
        uuid:
          type: string
          example: 123123
        permissions_name:
          type: string
          example: loan creating
    person:
      required:
        - first_name
        - middle_name
        - last_name
        - email
        - address
        - age
        - gender
        - date_of_birth
      type: object
      properties:
        uuid:
          type: string
          example: 123456
        first_name:
          type: string
          example: Ivan
        middle_name:
          type: string
          example: Ivanovich
        last_name:
          type: string
          example: Ivanov
        email:
          type: string
          example: ivanov.i@example.exp
        address:
          type: string
          example: Bashkortostan Republic, c. Ufa, str. Street, h. 21, app. 16
        age:
          type: integer
          example: 25
        gender:
          type: string
          example: male
        date_of_birth:
          type: string
          example: 14.11.1974


