openapi: 3.0.0
info:
  title: user_authorization service - OpenAPI 3.0
  description: |-
    Сервис авторизации пользователей
  version: 1.0.0
servers:
  - url: https://user-authorization.swagger.io/api/v1
tags:
  - name: users
    description: Everything about users
  - name: persons
    description: Everything about witches user person
  - name: user_roles
    description: Everything about user_roles
  - name: permissions
    description: Everything about permissions
  - role_permissions:
    description: Everything about role permissions
paths: