openapi: 3.0.0
info:
  title: user_authorization service - OpenAPI 3.0
  description: |-
    Сервис авторизации пользователей
  version: 1.0.0
servers:
  - url: https://user-authorization.swagger.io/api/v1
tags:
  - name: users
    description: Everything about users
paths:
  /users:
    get:
      tags:
        - users
      summary: Users list
      description: users list
      operationId: usersList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  - $ref: "#/components/schemas/user"
        '204':
          description: empty list
          content:
            application/json:
              schema:
                type: array
  /users/{uuid}:
    get:
      tags:
        - users
      summary: Find user by uuid
      description: returns a single user
      operationId: getUserByUUID
      parameters:
        - name: uuid
          in: path
          description: uuid of user to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        '400':
          description: invalid uuid supplied
        '404':
          description: user not found



components:
  schemas:
    user:
      required:
        - uuid
        - user_name
      type: object
      properties:
        uuid:
          type: string
          example: 123123
        user_name:
          type: string
          example: ivanov.i
